### ISSUE TITLE
Import Client: evaluar si existe cliente

### ISSUE THREAD

**Issue by teamq-ecuador** [teamq-ecuador/steffen-app#64]
Se debe evaluar si el cliente existe por Cellagon id y por internal_id (Nr Praxis)

**Comment by julioserpone** [comment]
Esto se corrige en proyecto [teamq-ecuador/erp](https://github.com/teamq-ecuador/teamq-erp/commit/3d3485142bd3405f9066097687ab5d1980d2ae87)
